### ISSUE TITLE
"pack" fails on Windows when ran on ImDisk ramdisks

### ISSUE THREAD

**Issue by smx-smx** [antangelo/xdvdfs#103]
`xdvdfs pack` faults when operating on ramdisks created with ImDisk toolkit:

```
> xdvdfs pack R:\files R:\output.iso
`error: Incorrect function. (os error 1)`
```

Repro steps:
- Create a ramdisk using https://sourceforge.net/projects/imdisk-toolkit/
- Put some files there
- `xdvdfs pack R:\files R:\output.iso`

Tested on commit 1cc850bf1b3487fad7ec7c9eed01d83e8fc75ba4

**Comment by antangelo** [comment]
In general this should be a bug with the filesystem; based on what I could find this error would imply it doesn't implement the particular operation we use for path canonicalization.

That being said, we can probably work around it with some tradeoffs in detecting output path validity, see if this works for you: https://github.com/antangelo/xdvdfs/pull/104

**Comment by smx-smx** [comment]
Thanks for the quick reply.
I tried the patch and i confirm it works now.
