### ISSUE TITLE
Feature Request: Add repack command.

### ISSUE THREAD

**Issue by rizaumami** [antangelo/xdvdfs#53]
`extract-xiso` has a feature to directly rewrite xiso (using `-r` switch). Would be nice if `xdvdfs` has a similar feature so we can directly "streaming" redump to xiso without intermediate/additional steps.

**Comment by antangelo** [comment]
You can pass an iso or xiso image as input to the `pack` subcommand to achieve this, does that fit your use case?

**Comment by rizaumami** [comment]
Ya, that'll do. Thank you.
