### ISSUE TITLE
Error: Too many entries in directory

### ISSUE THREAD

**Issue by rizaumami** [antangelo/xdvdfs#55]
Getting `Error: Too many entries in directory` when packing Tom Clancy's Rainbow Six - Critical Hour (USA) (En,Fr).iso'.
Either by directly repacking the iso:
```bash
xdvdfs pack Tom\ Clancy\'s\ Rainbow\ Six\ -\ Critical\ Hour\ \(USA\)\ \(En\,Fr\).iso test.iso
```
Or by unpacking first, and then repacking it:
```bash
xdvdfs unpack Tom\ Clancy\'s\ Rainbow\ Six\ -\ Critical\ Hour\ \(USA\)\ \(En\,Fr\).iso
xdvdfs pack Tom\ Clancy\'s\ Rainbow\ Six\ -\ Critical\ Hour\ \(USA\)\ \(En\,Fr\)

```

**Comment by antangelo** [comment]
If able, please compile https://github.com/antangelo/xdvdfs/pull/57 from source and verify that it solves the issue.

**Comment by rizaumami** [comment]
> If able, please compile #57 from source and verify that it solves the issue.

I've compiled the PR and verify that it's solved the issue. 
Thanx.
