### ISSUE TITLE
Garbage file data when extracting redump-formatted image.

### ISSUE THREAD

**Issue by Aerocatia** [antangelo/xdvdfs#56]
I attempted to extract an image of the Korean version of Halo: CE that is dumped according to redump.
While the file naming is correct, the files themselves are all garbage data and not what they should be.
extract-xiso (XboxDev fork) is able to extract the same image correctly.

**Comment by antangelo** [comment]
I have a hunch as to what the issue is. Can you try repacking the image with xdvdfs, then unpacking the result?

```sh
$ xdvdfs pack redump_image.iso repacked.iso
$ xdvdfs unpack repacked.iso
```

**Comment by Aerocatia** [comment]
That indeed works and all files match the output of extract-xiso.
