### ISSUE TITLE
The Safety of Minimized Binary Size

### ISSUE THREAD

**Issue by rizaumami** [antangelo/xdvdfs#61]
I compile this project using `cargo build --release`.

Default `Cargo.toml`:
```toml
[profile.release]
strip = "debuginfo"
lto = true
```
Generated 2,8 MB of compiled binary.
```sh
stat -c %s target/release/xdvdfs
2771112
```

Changing `strip` to `true` reduced binary size for a bit (don't care about breaking the `xdvdfs-web`)
```sh
stat -c %s target/release/xdvdfs
2357688
```

Following tips from [here](https://github.com/johnthagen/min-sized-rust):
```toml
[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
```

Reduced the binary output to:
```sh
stat -c %s target/release/xdvdfs
1747384
```
Quite nice. 1 MB smaller.
My question is; is it safe to use this config?
Safe as in not going to break core functionality such as pack, unpack, etc.

**Comment by antangelo** [comment]
It shouldn't break anything in theory, but I don't test using any configuration besides what is in tree.
