### ISSUE TITLE
Feature Request: Cerbios Compressed Image (CCI) Support

### ISSUE THREAD

**Issue by rizaumami** [antangelo/xdvdfs#62]
CCI stands for Cerbios Compression Image. And Cerbios is a currently popular custom ogxbox BIOS. 
The only tool I know capable to produce CCI is [Repackinator](https://github.com/Team-Resurgent/Repackinator).
But, that's all I know. I know nothing about the specificaton of CCI, etc.

Would be nice if `xdvdfs` also support this format.

**Comment by antangelo** [comment]
Thanks for the feature request! I don't have much interest in supporting additional compressed formats, CISO support is already somewhat out of the way in the codebase and I'd like to keep that as minimal as possible.

In cases where output images need post processing (especially outside of the web use case), it'd be better to build a dedicated tool for that specific purpose.
