### ISSUE TITLE
Accept Input from Stream

### ISSUE THREAD

**Issue by rizaumami** [antangelo/xdvdfs#63]
I have a little VPS with approx 15 GB usable space.
Using traditional method of downloading redump and then extracting it, it will probably left with 1 or 2 GB of space.
Is it possible to feed `xdvdfs` from stream piped by `unzip -p`? 
Perhaps like `unzip -p game.zip | xargs xdvdfs pack`? Well, I've tried it and obviously it doesn't works.

Thanx.

**Comment by antangelo** [comment]
Piracy and its related use cases are not supported by this tool.
