### ISSUE TITLE
Error: IOError: Entry does not exist

### ISSUE THREAD

**Issue by rizaumami** [antangelo/xdvdfs#64]
`xdvdfs` throw `Error: IOError: Entry does not exist` error when repack an already packed '007: Agent Under Fire' xiso.

How to repro:
- Pack 007: Agent Under Fire
- Then pack the packed xiso generated from step above

What's happens normally?
`xdvdfs` will happily repack an already packed xiso.

EDIT:  
Affected game:
- 007: Agent Under Fire
- Silent Hill 2: Restless Dreams

**Comment by antangelo** [comment]
Please build from trunk, run the pack command with `RUST_LOG=debug ...`, and post the tail of the logs from the last `Added file ...` or `DEBUG xdvdfs::read] [walk_path] Called` line until the error message.

**Comment by rizaumami** [comment]
[Uploading debug.log…]()

**Comment by antangelo** [comment]
What is the output of `xdvdfs info` on the path `/Assets/sound/dialog/alp1_2`?

**Comment by rizaumami** [comment]
> What is the output of `xdvdfs info` on the path `/Assets/sound/dialog/alp1_2`?

`Error: Entry does not exist`

I've mounted the xiso using `xbfuse`, and indeed `/Assets/sound/dialog/alp1_2` is an empty directory.

**Comment by antangelo** [comment]
Is that the full output of the command? Based on the other logs you've given me I expect more data to be returned.

If it is, then please post the full debug log from before (and possibly also a new debug log from that info command).

**Comment by rizaumami** [comment]
I've sent the pack debug.log in previous post.

Command below returns an empty log. 
`DEBUG_LOG=debug ./xdvdfs info 007\ -\ Agent\ Under\ Fire\ \(USA\).iso "/Assets/sound/dialog/alp1_2/alp1_2"`
Only printed in terminal: `Error: Entry does not exist`

**Comment by antangelo** [comment]
The previous debug log is truncated, I now want to inspect the full log.

The info command is also not correct, I need the info output for the parent directory `/Assets/sound/dialog/alp1_2`.

**Comment by antangelo** [comment]
Reproducing test case is an image with an empty directory in it
