### ISSUE TITLE
xdvdfs-cli MD5 command doesn't work with Redump images

### ISSUE THREAD

**Issue by astarivi** [antangelo/xdvdfs#95]
Redump images do not seem to work with the MD5 CLI command, the following error is printed out when trying to calculate the MD5:

`error: Not an XDVDFS volume`

**Comment by antangelo** [comment]
It looks like `cmd_md5` is not using `crate::img::open_image` to open the source, which accounts for the volume offsets. Probably an oversight from doing the original refactor.
